CREATE DATABASE IF NOT EXISTS login_task
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE login_task;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);